apiVersion: apps/v1
kind: Deployment
metadata:
  name: kute
spec:
  selector:
    matchLabels:
      app: kute
  replicas: 3
  template:
    metadata:
      labels:
        app: kute
    spec:
      containers:
        - name: kute
          image: zeio/kute:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kute-service
spec:
  type: NodePort
  selector:
    app: kute
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 8081
